# Generated by Django 6.0.8 on 2026-09-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=280)),
                ('timing', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], db_index=True, max_length=10)),
                ('registration_status', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('display_date', models.CharField(blank=True, max_length=120)),
                ('event_time', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=180)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('event_date', 'display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='InitiativeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('lead', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='initiatives/groups/')),
                ('link_to_events', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=280)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('lead', models.TextField(blank=True)),
                ('overview', models.JSONField(blank=True, default=list)),
                ('impact', models.JSONField(blank=True, default=list)),
                ('date_label', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('participants', models.CharField(blank=True, max_length=100)),
                ('initiative_status', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='initiatives/covers/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='initiatives.initiativegroup')),
            ],
            options={
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='InitiativeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='initiatives/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='initiatives.initiative')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
