# Generated by Django 6.0.8 on 2026-09-25 17:57

import apps.content.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=280)),
                ('guest', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=40)),
                ('published_date', models.DateField(blank=True, db_index=True, null=True)),
                ('display_date', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to='podcasts/episodes/')),
                ('audio_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-published_date', '-episode_number'),
            },
        ),
        migrations.CreateModel(
            name='PodcastShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Podcast', max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('lead', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('cover_image', models.ImageField(blank=True, upload_to='podcasts/covers/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('type', models.CharField(choices=[('article', 'Article'), ('issue_brief', 'Issue Brief'), ('bill_brief', 'Bill Brief'), ('book', 'Book'), ('report', 'Report')], db_index=True, max_length=20)),
                ('vertical', models.CharField(blank=True, db_index=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=180)),
                ('publication_date', models.DateField(blank=True, db_index=True, null=True)),
                ('display_date', models.CharField(blank=True, max_length=100)),
                ('cover_image', models.ImageField(blank=True, upload_to='publications/covers/')),
                ('document', models.FileField(blank=True, upload_to='publications/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx', 'doc', 'docx']), apps.content.models.validate_upload_size])),
                ('document_type', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ('-publication_date', 'title'),
            },
        ),
    ]
